# Full suite of mock_uss instances, capable of serving all local uss_qualifier tests.
# Requires the interoperability ecosystem that can be brought up with build/dev/run_locally.sh

# To bring up this system, see README.md

version: '3.8'

services:

  mock_uss_ridsp:
    container_name: mock_uss_ridsp
    hostname: v22a.ridsp.uss1.localutm
    image: interuss/monitoring
    command: mock_uss/start.sh
    environment:
      - MOCK_USS_AUTH_SPEC=DummyOAuth(http://oauth.authority.localutm:8085/token,uss1)
      - MOCK_USS_DSS_URL=http://dss.uss1.localutm
      - MOCK_USS_PUBLIC_KEY=/var/test-certs/auth2.pem
      - MOCK_USS_TOKEN_AUDIENCE=v22a.ridsp.uss1.localutm,localhost,host.docker.internal
      - MOCK_USS_BASE_URL=http://v22a.ridsp.uss1.localutm
      - MOCK_USS_SERVICES=ridsp
      - MOCK_USS_RID_VERSION=F3411-22a
      - MOCK_USS_PORT=80
    expose:
      - 80
    ports:
      - 8081:80
    volumes:
      - ../../build/test-certs:/var/test-certs:ro
    restart: always
    networks:
      - interop_ecosystem_network
    extra_hosts:
      - host.docker.internal:host-gateway

  mock_uss_riddp:
    container_name: mock_uss_riddp
    hostname: v22a.riddp.uss1.localutm
    image: interuss/monitoring
    command: mock_uss/start.sh
    environment:
      - MOCK_USS_AUTH_SPEC=DummyOAuth(http://oauth.authority.localutm:8085/token,uss1)
      - MOCK_USS_DSS_URL=http://dss.uss1.localutm
      - MOCK_USS_PUBLIC_KEY=/var/test-certs/auth2.pem
      - MOCK_USS_TOKEN_AUDIENCE=v22a.riddp.uss1.localutm,localhost,host.docker.internal
      - MOCK_USS_BASE_URL=http://v22a.riddp.uss1.localutm
      - MOCK_USS_SERVICES=riddp
      - MOCK_USS_RID_VERSION=F3411-22a
      - MOCK_USS_PORT=80
    expose:
      - 80
    ports:
      - 8083:80
    volumes:
      - ../../build/test-certs:/var/test-certs:ro
    restart: always
    networks:
      - interop_ecosystem_network
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  interop_ecosystem_network:
    external: true
